name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Обновлено на v3 для последней версии

    - name: Set up Python
      uses: actions/setup-python@v3  # Обновлено на v3 для последней версии
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Build Docker image
      run: docker build -t my-devops-app .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Tag Docker image
      run: docker tag my-devops-app ${{ secrets.DOCKER_HUB_USERNAME }}/my-devops-app:latest

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-devops-app:latest
